/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ClaimEvaluatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimExists"
      | "confidentialProtocolId"
      | "evaluateClaim"
      | "getClaim"
      | "getClaimCount"
      | "getLossAmount"
      | "getPayout"
      | "getRiskLevel"
      | "submitClaim"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ClaimEvaluated" | "ClaimSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLossAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitClaim",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLossAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayout", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRiskLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitClaim",
    data: BytesLike
  ): Result;
}

export namespace ClaimEvaluatedEvent {
  export type InputTuple = [claimId: BigNumberish];
  export type OutputTuple = [claimId: bigint];
  export interface OutputObject {
    claimId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimSubmittedEvent {
  export type InputTuple = [claimId: BigNumberish, claimant: AddressLike];
  export type OutputTuple = [claimId: bigint, claimant: string];
  export interface OutputObject {
    claimId: bigint;
    claimant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClaimEvaluator extends BaseContract {
  connect(runner?: ContractRunner | null): ClaimEvaluator;
  waitForDeployment(): Promise<this>;

  interface: ClaimEvaluatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimExists: TypedContractMethod<[claimId: BigNumberish], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  evaluateClaim: TypedContractMethod<
    [claimId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getClaim: TypedContractMethod<
    [claimId: BigNumberish],
    [
      [string, string, string] & {
        lossAmount: string;
        riskLevel: string;
        payout: string;
      }
    ],
    "view"
  >;

  getClaimCount: TypedContractMethod<[], [bigint], "view">;

  getLossAmount: TypedContractMethod<[claimId: BigNumberish], [string], "view">;

  getPayout: TypedContractMethod<[claimId: BigNumberish], [string], "view">;

  getRiskLevel: TypedContractMethod<[claimId: BigNumberish], [string], "view">;

  submitClaim: TypedContractMethod<
    [
      lossAmountEuint32: BytesLike,
      riskLevelEuint32: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimExists"
  ): TypedContractMethod<[claimId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "evaluateClaim"
  ): TypedContractMethod<[claimId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaim"
  ): TypedContractMethod<
    [claimId: BigNumberish],
    [
      [string, string, string] & {
        lossAmount: string;
        riskLevel: string;
        payout: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLossAmount"
  ): TypedContractMethod<[claimId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPayout"
  ): TypedContractMethod<[claimId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRiskLevel"
  ): TypedContractMethod<[claimId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "submitClaim"
  ): TypedContractMethod<
    [
      lossAmountEuint32: BytesLike,
      riskLevelEuint32: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimEvaluated"
  ): TypedContractEvent<
    ClaimEvaluatedEvent.InputTuple,
    ClaimEvaluatedEvent.OutputTuple,
    ClaimEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimSubmitted"
  ): TypedContractEvent<
    ClaimSubmittedEvent.InputTuple,
    ClaimSubmittedEvent.OutputTuple,
    ClaimSubmittedEvent.OutputObject
  >;

  filters: {
    "ClaimEvaluated(uint256)": TypedContractEvent<
      ClaimEvaluatedEvent.InputTuple,
      ClaimEvaluatedEvent.OutputTuple,
      ClaimEvaluatedEvent.OutputObject
    >;
    ClaimEvaluated: TypedContractEvent<
      ClaimEvaluatedEvent.InputTuple,
      ClaimEvaluatedEvent.OutputTuple,
      ClaimEvaluatedEvent.OutputObject
    >;

    "ClaimSubmitted(uint256,address)": TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;
    ClaimSubmitted: TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;
  };
}
